---
- name: Pre tasks
  hosts: all
  pre_tasks:
    - name: Verify Ansible is version 2.11 or above. (If this fails you may need to update Ansible)
      ansible.builtin.assert:
        that: ansible_version.full is version_compare('2.11', '>=')
        msg: >
          "Ansible is out of date. See here for more info: https://docs.technotim.live/posts/ansible-automation/"


- name: Harden k3s Nodes
  hosts: k3s_cluster
  roles:
    - role: devsec.hardening.os_hardening
      become: true
      when: harden_k3s_nodes
    - role: devsec.hardening.ssh_hardening
      become: true
      when: harden_k3s_nodes
  tags:
    - harden

- name: Prepare k3s nodes
  hosts: k3s_cluster
  gather_facts: true
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: prereq
      become: true
    - role: download
      become: true
    - role: k3s_custom_registries
      become: true
      when: custom_registries

- name: Setup k3s servers
  hosts: master
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: k3s_server
      become: true

- name: Setup k3s agents
  hosts: node
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: k3s_agent
      become: true

- name: Deploy Cilium CNI
  hosts: master
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: cilium
      become: true

- name: Deploy Longhorn CSI
  hosts: master
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: longhorn
      become: true

- name: Deploy Cert Manager
  hosts: master
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: cert_manager
      become: true

- name: Storing kubeconfig in the playbook directory
  hosts: master
  environment: "{{ proxy_env | default({}) }}"
  tasks:
    - name: Copying kubeconfig from {{ hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname'] }}
      ansible.builtin.fetch:
        src: "{{ ansible_user_dir }}/.kube/config"
        dest: ./kubeconfig
        flat: true
      when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']
