apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-traffic-to-kube-api
spec:
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/control-plane: ''
  ingress:
  - fromCIDR:
    - "{{ apiserver_endpoint }}/32"
    toPorts:
    - ports:
      - port: '6443'
        protocol: TCP
  egress:
  # api server -> kubelet
  - toEntities:
    - remote-node
    toPorts:
    - ports:
      - port: '10250'
        protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: kubelet
spec:
  nodeSelector:
    matchLabels: {}
  ingress:
  - fromEntities:
    - kube-apiserver
    toPorts:
    - ports:
      - port: '10250'
        protocol: TCP
  egress:
  - toCIDR:
    - "{{ apiserver_endpoint }}/32"
    toPorts:
    - ports:
      - port: '6443'
        protocol: TCP