---
- name: Create manifests directory on first master
  ansible.builtin.file:
    path: /var/lib/rancher/k3s/server/manifests/auth
    state: directory
    owner: root
    group: root
    mode: "0644"
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']
  tags:
    - auth

- name: Create Dex chart manifest on first master
  ansible.builtin.template:
    src: dex-chart.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/cm/dex-chart.yaml
    owner: root
    group: root
    mode: "0644"
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']
  tags:
    - auth

- name: Wait for Dex resources
  ansible.builtin.command: >-
    {% if item.type == 'daemonset' %}
    {{ k3s_kubectl_binary | default('k3s kubectl') }} wait pods
    --namespace={{ cm_namespace }}
    --selector={{ item.selector }}
    --for=condition=Ready
    {% else %}
    {{ k3s_kubectl_binary | default('k3s kubectl') }} wait {{ item.type }}/{{ item.name }}
    --namespace={{ cm_namespace }}
    --for=condition=Available
    {% endif %}
    --timeout={{ cm_check_timeout }}
  register: cr_result
  changed_when: false
  until: cr_result is succeeded
  retries: 30
  delay: 7
  with_items: []
  loop_control:
    label: "{{ item.type }}/{{ item.name }}"
  tags:
    - auth
