---
- name: Create manifests directory for temp configuration
  ansible.builtin.file:
    path: /tmp/k3s
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: "0755"
  with_items: "{{ groups[group_name_master | default('master')] }}"
  run_once: true

- name: Test cnpg-system namespace
  ansible.builtin.command: >-
    k3s kubectl -n cnpg-system
  changed_when: false
  with_items: "{{ groups[group_name_master | default('master')] }}"
  run_once: true

- name: Wait for cnpg resources
  ansible.builtin.command: >-
    k3s kubectl wait {{ item.resource }}
    --namespace='cnpg-system'
    {% if item.name | default(False) -%}{{ item.name }}{%- endif %}
    {% if item.selector | default(False) -%}--selector='{{ item.selector }}'{%- endif %}
    {% if item.condition | default(False) -%}{{ item.condition }}{%- endif %}
    --timeout='{{ cnpg_available_timeout }}'
  changed_when: false
  run_once: true
  with_items:
    - description: controller
      resource: deployment
      name: cnpg-controller-manager
      condition: --for condition=Available=True
  loop_control:
    label: "{{ item.description }}"
